# Release automation via GoReleaser (goreleaser.com)
# Requires a valid GITHUB_TOKEN envar prior to running `goreleaser`
# See https://goreleaser.com/environment/ for more info
---
release:
  github:
    owner: ashkan90
    name: auto-cli

builds:
  - binary: auto-cli
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=proxy.golang.org
      - GOSUMDB=sum.golang.org
    main: ./

snapshot:
  name_template: "snap-{{ .Commit }}"
